version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile.dev}
    image: ai-scan-frontend
    ports:
      - "5173:5173" # dev server port(not in production obviously)
      - "8080:80" # optional mapping if using production image
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ai_scan}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
